# Use Node 20 as base image
FROM node:20

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Copy environment variables
COPY .env .env

# Expose the app's port
EXPOSE 8000

# Start the app
CMD ["node", "src/index.js"]
